---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - sudo make docker-build
  image: zachfi/shell:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
  - refs/pull/*/head
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
depends_on: []
kind: pipeline
name: release
steps:
- commands:
  - make release
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  image: zachfi/build-image
  name: release
  pull: always
  when:
    ref:
    - refs/tags/v*
trigger:
  ref:
  - refs/tags/v*
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: d8b21b1c28ee60b3911b26b86fd17b4d24ca9d0e800d0316784f33b48e5ad6a4

...
