kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - make docker-build
  image: zachfi/shell:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
