---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: zachfi/build-image:latest
  name: test
- commands:
  - sudo make docker-build registry=reg.dist.svc.cluster.znet:5000
  image: zachfi/build-image:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  when:
    ref:
    - refs/heads/main
- commands:
  - sudo make docker-push registry=reg.dist.svc.cluster.znet:5000
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  image: zachfi/build-image:latest
  name: push-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  when:
    ref:
    - refs/heads/main
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
  - refs/pull/*/head
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
depends_on: []
kind: pipeline
name: release
steps:
- commands:
  - make release
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  image: zachfi/build-image:latest
  name: release
  pull: always
  when:
    ref:
    - refs/tags/v*
trigger:
  ref:
  - refs/tags/v*
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: e21e83649b884e554caa22fa98e5b7caba6621812892cb24dcb299d42a660d3e

...
