---
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - make docker-build
  image: zachfi/shell:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
---
kind: signature
hmac: 92b6c5f98a0b29d96585ba600c042d1237c8d6498ef8a6fb2151e126bdeccbe3

...
