---
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - sudo make docker-build
  image: zachfi/shell:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
---
kind: signature
hmac: f60c21b9df7812a3c51f5e22980788b0f6621acdc64df5d307f29197332de6b0

...
