---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - sudo make docker-build
  image: zachfi/shell:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: 8a3d73e5d57c8d8bca329c74c9f1f3c6639910e90d8fa3cca1b1ae8169d7181d

...
