---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - make test-e2e
  image: reg.dist.svc.cluster.znet:5000/zachfi/build-image
  name: test-e2e
  pull: always
- commands:
  - sudo make docker-build registry=reg.dist.svc.cluster.znet:5000
  image: reg.dist.svc.cluster.znet:5000/zachfi/build-image
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  when:
    ref:
    - refs/heads/main
- commands:
  - sudo make docker-push registry=reg.dist.svc.cluster.znet:5000
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  image: reg.dist.svc.cluster.znet:5000/zachfi/build-image
  name: push-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  when:
    ref:
    - refs/heads/main
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
  - refs/pull/*/head
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
depends_on: []
kind: pipeline
name: release
steps:
- commands:
  - make release
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  image: reg.dist.svc.cluster.znet:5000/zachfi/build-image
  name: release
  pull: always
  when:
    ref:
    - refs/tags/v*
trigger:
  ref:
  - refs/tags/v*
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: bc94205a1cadfa003e401bc93958edb765ed79643b18fae26ebc891ff476d6a7

...
