---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - sudo make docker-build
  image: zachfi/shell:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
  - refs/tags/v*
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: c9516590ac7b912692767ebaaa999c684f21f74aa901b8e7a27696b3e667f7da

...
