---
depends_on: []
kind: pipeline
name: ci
steps:
- commands:
  - make test
  image: golang
  name: test
- commands:
  - sudo make docker-build
  image: zachfi/shell:latest
  name: build-image
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
trigger:
  ref:
  - refs/heads/main
  - refs/heads/dependabot/**
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
depends_on: []
kind: pipeline
name: release
steps:
- commands:
  - make release
  environment:
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
  image: zachfi/build-image
  name: release
  pull: always
  when:
    ref:
    - refs/tags/v*
trigger:
  ref:
  - refs/tags/v*
volumes:
- host:
    path: /var/run/docker.sock
  name: dockersock
---
kind: signature
hmac: 6cd264b3f3b86a2f70aa2a73fca84800961bab609c6401f8430043126be8649d

...
