// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: iot/v1/iot.proto

package iotv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColorTemperature int32

const (
	ColorTemperature_COLOR_TEMPERATURE_UNSPECIFIED   ColorTemperature = 0
	ColorTemperature_COLOR_TEMPERATURE_FIRSTLIGHT    ColorTemperature = 1
	ColorTemperature_COLOR_TEMPERATURE_MORNING       ColorTemperature = 2
	ColorTemperature_COLOR_TEMPERATURE_DAY           ColorTemperature = 3
	ColorTemperature_COLOR_TEMPERATURE_LATEAFTERNOON ColorTemperature = 4
	ColorTemperature_COLOR_TEMPERATURE_EVENING       ColorTemperature = 5
)

// Enum value maps for ColorTemperature.
var (
	ColorTemperature_name = map[int32]string{
		0: "COLOR_TEMPERATURE_UNSPECIFIED",
		1: "COLOR_TEMPERATURE_FIRSTLIGHT",
		2: "COLOR_TEMPERATURE_MORNING",
		3: "COLOR_TEMPERATURE_DAY",
		4: "COLOR_TEMPERATURE_LATEAFTERNOON",
		5: "COLOR_TEMPERATURE_EVENING",
	}
	ColorTemperature_value = map[string]int32{
		"COLOR_TEMPERATURE_UNSPECIFIED":   0,
		"COLOR_TEMPERATURE_FIRSTLIGHT":    1,
		"COLOR_TEMPERATURE_MORNING":       2,
		"COLOR_TEMPERATURE_DAY":           3,
		"COLOR_TEMPERATURE_LATEAFTERNOON": 4,
		"COLOR_TEMPERATURE_EVENING":       5,
	}
)

func (x ColorTemperature) Enum() *ColorTemperature {
	p := new(ColorTemperature)
	*p = x
	return p
}

func (x ColorTemperature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorTemperature) Descriptor() protoreflect.EnumDescriptor {
	return file_iot_v1_iot_proto_enumTypes[0].Descriptor()
}

func (ColorTemperature) Type() protoreflect.EnumType {
	return &file_iot_v1_iot_proto_enumTypes[0]
}

func (x ColorTemperature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorTemperature.Descriptor instead.
func (ColorTemperature) EnumDescriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{0}
}

type Brightness int32

const (
	Brightness_BRIGHTNESS_UNSPECIFIED Brightness = 0
	Brightness_BRIGHTNESS_FULL        Brightness = 1
	Brightness_BRIGHTNESS_DIM         Brightness = 2
	Brightness_BRIGHTNESS_LOW         Brightness = 3
	Brightness_BRIGHTNESS_DIMPLUS     Brightness = 4
	Brightness_BRIGHTNESS_LOWPLUS     Brightness = 5
	Brightness_BRIGHTNESS_VERYLOW     Brightness = 6
)

// Enum value maps for Brightness.
var (
	Brightness_name = map[int32]string{
		0: "BRIGHTNESS_UNSPECIFIED",
		1: "BRIGHTNESS_FULL",
		2: "BRIGHTNESS_DIM",
		3: "BRIGHTNESS_LOW",
		4: "BRIGHTNESS_DIMPLUS",
		5: "BRIGHTNESS_LOWPLUS",
		6: "BRIGHTNESS_VERYLOW",
	}
	Brightness_value = map[string]int32{
		"BRIGHTNESS_UNSPECIFIED": 0,
		"BRIGHTNESS_FULL":        1,
		"BRIGHTNESS_DIM":         2,
		"BRIGHTNESS_LOW":         3,
		"BRIGHTNESS_DIMPLUS":     4,
		"BRIGHTNESS_LOWPLUS":     5,
		"BRIGHTNESS_VERYLOW":     6,
	}
)

func (x Brightness) Enum() *Brightness {
	p := new(Brightness)
	*p = x
	return p
}

func (x Brightness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Brightness) Descriptor() protoreflect.EnumDescriptor {
	return file_iot_v1_iot_proto_enumTypes[1].Descriptor()
}

func (Brightness) Type() protoreflect.EnumType {
	return &file_iot_v1_iot_proto_enumTypes[1]
}

func (x Brightness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Brightness.Descriptor instead.
func (Brightness) EnumDescriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{1}
}

type ZoneState int32

const (
	ZoneState_ZONE_STATE_UNSPECIFIED ZoneState = 0
	ZoneState_ZONE_STATE_ON          ZoneState = 1
	ZoneState_ZONE_STATE_OFF         ZoneState = 2
	ZoneState_ZONE_STATE_OFFTIMER    ZoneState = 3
	ZoneState_ZONE_STATE_COLOR       ZoneState = 4
	ZoneState_ZONE_STATE_RANDOMCOLOR ZoneState = 5
)

// Enum value maps for ZoneState.
var (
	ZoneState_name = map[int32]string{
		0: "ZONE_STATE_UNSPECIFIED",
		1: "ZONE_STATE_ON",
		2: "ZONE_STATE_OFF",
		3: "ZONE_STATE_OFFTIMER",
		4: "ZONE_STATE_COLOR",
		5: "ZONE_STATE_RANDOMCOLOR",
	}
	ZoneState_value = map[string]int32{
		"ZONE_STATE_UNSPECIFIED": 0,
		"ZONE_STATE_ON":          1,
		"ZONE_STATE_OFF":         2,
		"ZONE_STATE_OFFTIMER":    3,
		"ZONE_STATE_COLOR":       4,
		"ZONE_STATE_RANDOMCOLOR": 5,
	}
)

func (x ZoneState) Enum() *ZoneState {
	p := new(ZoneState)
	*p = x
	return p
}

func (x ZoneState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneState) Descriptor() protoreflect.EnumDescriptor {
	return file_iot_v1_iot_proto_enumTypes[2].Descriptor()
}

func (ZoneState) Type() protoreflect.EnumType {
	return &file_iot_v1_iot_proto_enumTypes[2]
}

func (x ZoneState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneState.Descriptor instead.
func (ZoneState) EnumDescriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{2}
}

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_COORDINATOR DeviceType = 1
	DeviceType_DEVICE_TYPE_BASIC_LIGHT DeviceType = 2
	DeviceType_DEVICE_TYPE_COLOR_LIGHT DeviceType = 3
	DeviceType_DEVICE_TYPE_RELAY       DeviceType = 4
	DeviceType_DEVICE_TYPE_LEAK        DeviceType = 5
	DeviceType_DEVICE_TYPE_BUTTON      DeviceType = 6
	DeviceType_DEVICE_TYPE_MOISTURE    DeviceType = 7
	DeviceType_DEVICE_TYPE_TEMPERATURE DeviceType = 8
	DeviceType_DEVICE_TYPE_MOTION      DeviceType = 9
	DeviceType_DEVICE_TYPE_ISPINDEL    DeviceType = 10
	DeviceType_DEVICE_TYPE_SOIL        DeviceType = 11
	DeviceType_DEVICE_TYPE_AIR_QUALITY DeviceType = 12
	DeviceType_DEVICE_TYPE_ROUTER      DeviceType = 13
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0:  "DEVICE_TYPE_UNSPECIFIED",
		1:  "DEVICE_TYPE_COORDINATOR",
		2:  "DEVICE_TYPE_BASIC_LIGHT",
		3:  "DEVICE_TYPE_COLOR_LIGHT",
		4:  "DEVICE_TYPE_RELAY",
		5:  "DEVICE_TYPE_LEAK",
		6:  "DEVICE_TYPE_BUTTON",
		7:  "DEVICE_TYPE_MOISTURE",
		8:  "DEVICE_TYPE_TEMPERATURE",
		9:  "DEVICE_TYPE_MOTION",
		10: "DEVICE_TYPE_ISPINDEL",
		11: "DEVICE_TYPE_SOIL",
		12: "DEVICE_TYPE_AIR_QUALITY",
		13: "DEVICE_TYPE_ROUTER",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_COORDINATOR": 1,
		"DEVICE_TYPE_BASIC_LIGHT": 2,
		"DEVICE_TYPE_COLOR_LIGHT": 3,
		"DEVICE_TYPE_RELAY":       4,
		"DEVICE_TYPE_LEAK":        5,
		"DEVICE_TYPE_BUTTON":      6,
		"DEVICE_TYPE_MOISTURE":    7,
		"DEVICE_TYPE_TEMPERATURE": 8,
		"DEVICE_TYPE_MOTION":      9,
		"DEVICE_TYPE_ISPINDEL":    10,
		"DEVICE_TYPE_SOIL":        11,
		"DEVICE_TYPE_AIR_QUALITY": 12,
		"DEVICE_TYPE_ROUTER":      13,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_iot_v1_iot_proto_enumTypes[3].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_iot_v1_iot_proto_enumTypes[3]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{3}
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{0}
}

// <discovery_prefix>/<component>/[<node_id>/]<object_id>/config
type DeviceDiscovery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryPrefix string                 `protobuf:"bytes,1,opt,name=discovery_prefix,json=discoveryPrefix,proto3" json:"discovery_prefix,omitempty"`
	Component       string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	NodeId          string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ObjectId        string                 `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Endpoints       []string               `protobuf:"bytes,5,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Message         []byte                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeviceDiscovery) Reset() {
	*x = DeviceDiscovery{}
	mi := &file_iot_v1_iot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDiscovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDiscovery) ProtoMessage() {}

func (x *DeviceDiscovery) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDiscovery.ProtoReflect.Descriptor instead.
func (*DeviceDiscovery) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceDiscovery) GetDiscoveryPrefix() string {
	if x != nil {
		return x.DiscoveryPrefix
	}
	return ""
}

func (x *DeviceDiscovery) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *DeviceDiscovery) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeviceDiscovery) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DeviceDiscovery) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *DeviceDiscovery) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type UpdateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDeviceRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type AlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRequest) Reset() {
	*x = AlertRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRequest) ProtoMessage() {}

func (x *AlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRequest.ProtoReflect.Descriptor instead.
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{3}
}

func (x *AlertRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AlertRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type AlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertResponse) Reset() {
	*x = AlertResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertResponse) ProtoMessage() {}

func (x *AlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertResponse.ProtoReflect.Descriptor instead.
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{4}
}

type EpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	When          int64                  `protobuf:"varint,3,opt,name=when,proto3" json:"when,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochRequest) Reset() {
	*x = EpochRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochRequest) ProtoMessage() {}

func (x *EpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochRequest.ProtoReflect.Descriptor instead.
func (*EpochRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{5}
}

func (x *EpochRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EpochRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *EpochRequest) GetWhen() int64 {
	if x != nil {
		return x.When
	}
	return 0
}

type EpochResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochResponse) Reset() {
	*x = EpochResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochResponse) ProtoMessage() {}

func (x *EpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochResponse.ProtoReflect.Descriptor instead.
func (*EpochResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{6}
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{7}
}

func (x *SendRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SendRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{8}
}

type SetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateResponse) Reset() {
	*x = SetStateResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateResponse) ProtoMessage() {}

func (x *SetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateResponse.ProtoReflect.Descriptor instead.
func (*SetStateResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{9}
}

type SetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // The name of the zone
	State         ZoneState              `protobuf:"varint,2,opt,name=state,proto3,enum=iot.v1.ZoneState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{10}
}

func (x *SetStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetStateRequest) GetState() ZoneState {
	if x != nil {
		return x.State
	}
	return ZoneState_ZONE_STATE_UNSPECIFIED
}

type SetSceneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSceneResponse) Reset() {
	*x = SetSceneResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSceneResponse) ProtoMessage() {}

func (x *SetSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSceneResponse.ProtoReflect.Descriptor instead.
func (*SetSceneResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{11}
}

type SetSceneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // The name of the zone
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSceneRequest) Reset() {
	*x = SetSceneRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSceneRequest) ProtoMessage() {}

func (x *SetSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSceneRequest.ProtoReflect.Descriptor instead.
func (*SetSceneRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{12}
}

func (x *SetSceneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetSceneRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

type GetDeviceZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceZoneRequest) Reset() {
	*x = GetDeviceZoneRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceZoneRequest) ProtoMessage() {}

func (x *GetDeviceZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceZoneRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceZoneRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{13}
}

func (x *GetDeviceZoneRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type GetDeviceZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceZoneResponse) Reset() {
	*x = GetDeviceZoneResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceZoneResponse) ProtoMessage() {}

func (x *GetDeviceZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceZoneResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceZoneResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{14}
}

func (x *GetDeviceZoneResponse) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type ActionHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Zone          string                 `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionHandlerRequest) Reset() {
	*x = ActionHandlerRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionHandlerRequest) ProtoMessage() {}

func (x *ActionHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionHandlerRequest.ProtoReflect.Descriptor instead.
func (*ActionHandlerRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{15}
}

func (x *ActionHandlerRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *ActionHandlerRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ActionHandlerRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type ActionHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionHandlerResponse) Reset() {
	*x = ActionHandlerResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionHandlerResponse) ProtoMessage() {}

func (x *ActionHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionHandlerResponse.ProtoReflect.Descriptor instead.
func (*ActionHandlerResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{16}
}

type SelfAnnounceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Zone          string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfAnnounceRequest) Reset() {
	*x = SelfAnnounceRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfAnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfAnnounceRequest) ProtoMessage() {}

func (x *SelfAnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfAnnounceRequest.ProtoReflect.Descriptor instead.
func (*SelfAnnounceRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{17}
}

func (x *SelfAnnounceRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *SelfAnnounceRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type SelfAnnounceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfAnnounceResponse) Reset() {
	*x = SelfAnnounceResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfAnnounceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfAnnounceResponse) ProtoMessage() {}

func (x *SelfAnnounceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfAnnounceResponse.ProtoReflect.Descriptor instead.
func (*SelfAnnounceResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{18}
}

type OccupancyHandlerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Device          string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Zone            string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	DurationSeconds string                 `protobuf:"bytes,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OccupancyHandlerRequest) Reset() {
	*x = OccupancyHandlerRequest{}
	mi := &file_iot_v1_iot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupancyHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyHandlerRequest) ProtoMessage() {}

func (x *OccupancyHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyHandlerRequest.ProtoReflect.Descriptor instead.
func (*OccupancyHandlerRequest) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{19}
}

func (x *OccupancyHandlerRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *OccupancyHandlerRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *OccupancyHandlerRequest) GetDurationSeconds() string {
	if x != nil {
		return x.DurationSeconds
	}
	return ""
}

type OccupancyHandlerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OccupancyHandlerResponse) Reset() {
	*x = OccupancyHandlerResponse{}
	mi := &file_iot_v1_iot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OccupancyHandlerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OccupancyHandlerResponse) ProtoMessage() {}

func (x *OccupancyHandlerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OccupancyHandlerResponse.ProtoReflect.Descriptor instead.
func (*OccupancyHandlerResponse) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{20}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DeviceType             `protobuf:"varint,2,opt,name=type,proto3,enum=iot.v1.DeviceType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_iot_v1_iot_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_iot_v1_iot_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_iot_v1_iot_proto_rawDescGZIP(), []int{21}
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

var File_iot_v1_iot_proto protoreflect.FileDescriptor

const file_iot_v1_iot_proto_rawDesc = "" +
	"\n" +
	"\x10iot/v1/iot.proto\x12\x06iot.v1\"\x16\n" +
	"\x14UpdateDeviceResponse\"\xc8\x01\n" +
	"\x0fDeviceDiscovery\x12)\n" +
	"\x10discovery_prefix\x18\x01 \x01(\tR\x0fdiscoveryPrefix\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\tR\bobjectId\x12\x1c\n" +
	"\tendpoints\x18\x05 \x03(\tR\tendpoints\x12\x18\n" +
	"\amessage\x18\x06 \x01(\fR\amessage\"-\n" +
	"\x13UpdateDeviceRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"N\n" +
	"\fAlertRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\"\x0f\n" +
	"\rAlertResponse\"R\n" +
	"\fEpochRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x12\n" +
	"\x04when\x18\x03 \x01(\x03R\x04when\"\x0f\n" +
	"\rEpochResponse\";\n" +
	"\vSendRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"\x0e\n" +
	"\fSendResponse\"\x12\n" +
	"\x10SetStateResponse\"N\n" +
	"\x0fSetStateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x05state\x18\x02 \x01(\x0e2\x11.iot.v1.ZoneStateR\x05state\"\x12\n" +
	"\x10SetSceneResponse\";\n" +
	"\x0fSetSceneRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\".\n" +
	"\x14GetDeviceZoneRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"+\n" +
	"\x15GetDeviceZoneResponse\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\"X\n" +
	"\x14ActionHandlerRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\"\x17\n" +
	"\x15ActionHandlerResponse\"A\n" +
	"\x13SelfAnnounceRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\"\x16\n" +
	"\x14SelfAnnounceResponse\"p\n" +
	"\x17OccupancyHandlerRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\tR\x0fdurationSeconds\"\x1a\n" +
	"\x18OccupancyHandlerResponse\"D\n" +
	"\x06Device\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.iot.v1.DeviceTypeR\x04type*\xd5\x01\n" +
	"\x10ColorTemperature\x12!\n" +
	"\x1dCOLOR_TEMPERATURE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCOLOR_TEMPERATURE_FIRSTLIGHT\x10\x01\x12\x1d\n" +
	"\x19COLOR_TEMPERATURE_MORNING\x10\x02\x12\x19\n" +
	"\x15COLOR_TEMPERATURE_DAY\x10\x03\x12#\n" +
	"\x1fCOLOR_TEMPERATURE_LATEAFTERNOON\x10\x04\x12\x1d\n" +
	"\x19COLOR_TEMPERATURE_EVENING\x10\x05*\xad\x01\n" +
	"\n" +
	"Brightness\x12\x1a\n" +
	"\x16BRIGHTNESS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fBRIGHTNESS_FULL\x10\x01\x12\x12\n" +
	"\x0eBRIGHTNESS_DIM\x10\x02\x12\x12\n" +
	"\x0eBRIGHTNESS_LOW\x10\x03\x12\x16\n" +
	"\x12BRIGHTNESS_DIMPLUS\x10\x04\x12\x16\n" +
	"\x12BRIGHTNESS_LOWPLUS\x10\x05\x12\x16\n" +
	"\x12BRIGHTNESS_VERYLOW\x10\x06*\x99\x01\n" +
	"\tZoneState\x12\x1a\n" +
	"\x16ZONE_STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rZONE_STATE_ON\x10\x01\x12\x12\n" +
	"\x0eZONE_STATE_OFF\x10\x02\x12\x17\n" +
	"\x13ZONE_STATE_OFFTIMER\x10\x03\x12\x14\n" +
	"\x10ZONE_STATE_COLOR\x10\x04\x12\x1a\n" +
	"\x16ZONE_STATE_RANDOMCOLOR\x10\x05*\xf9\x02\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DEVICE_TYPE_COORDINATOR\x10\x01\x12\x1b\n" +
	"\x17DEVICE_TYPE_BASIC_LIGHT\x10\x02\x12\x1b\n" +
	"\x17DEVICE_TYPE_COLOR_LIGHT\x10\x03\x12\x15\n" +
	"\x11DEVICE_TYPE_RELAY\x10\x04\x12\x14\n" +
	"\x10DEVICE_TYPE_LEAK\x10\x05\x12\x16\n" +
	"\x12DEVICE_TYPE_BUTTON\x10\x06\x12\x18\n" +
	"\x14DEVICE_TYPE_MOISTURE\x10\a\x12\x1b\n" +
	"\x17DEVICE_TYPE_TEMPERATURE\x10\b\x12\x16\n" +
	"\x12DEVICE_TYPE_MOTION\x10\t\x12\x18\n" +
	"\x14DEVICE_TYPE_ISPINDEL\x10\n" +
	"\x12\x14\n" +
	"\x10DEVICE_TYPE_SOIL\x10\v\x12\x1b\n" +
	"\x17DEVICE_TYPE_AIR_QUALITY\x10\f\x12\x16\n" +
	"\x12DEVICE_TYPE_ROUTER\x10\r2W\n" +
	"\n" +
	"IOTService\x12I\n" +
	"\fUpdateDevice\x12\x1b.iot.v1.UpdateDeviceRequest\x1a\x1c.iot.v1.UpdateDeviceResponse2\x82\x01\n" +
	"\x14EventReceiverService\x124\n" +
	"\x05Alert\x12\x14.iot.v1.AlertRequest\x1a\x15.iot.v1.AlertResponse\x124\n" +
	"\x05Epoch\x12\x14.iot.v1.EpochRequest\x1a\x15.iot.v1.EpochResponse2A\n" +
	"\fRouteService\x121\n" +
	"\x04Send\x12\x13.iot.v1.SendRequest\x1a\x14.iot.v1.SendResponse2\xcf\x03\n" +
	"\x11ZoneKeeperService\x12=\n" +
	"\bSetState\x12\x17.iot.v1.SetStateRequest\x1a\x18.iot.v1.SetStateResponse\x12=\n" +
	"\bSetScene\x12\x17.iot.v1.SetSceneRequest\x1a\x18.iot.v1.SetSceneResponse\x12L\n" +
	"\rGetDeviceZone\x12\x1c.iot.v1.GetDeviceZoneRequest\x1a\x1d.iot.v1.GetDeviceZoneResponse\x12L\n" +
	"\rActionHandler\x12\x1c.iot.v1.ActionHandlerRequest\x1a\x1d.iot.v1.ActionHandlerResponse\x12I\n" +
	"\fSelfAnnounce\x12\x1b.iot.v1.SelfAnnounceRequest\x1a\x1c.iot.v1.SelfAnnounceResponse\x12U\n" +
	"\x10OccupancyHandler\x12\x1f.iot.v1.OccupancyHandlerRequest\x1a .iot.v1.OccupancyHandlerResponseB\x83\x01\n" +
	"\n" +
	"com.iot.v1B\bIotProtoP\x01Z2github.com/zachfi/iotcontroller/proto/iot/v1;iotv1\xa2\x02\x03IXX\xaa\x02\x06Iot.V1\xca\x02\x06Iot\\V1\xe2\x02\x12Iot\\V1\\GPBMetadata\xea\x02\aIot::V1b\x06proto3"

var (
	file_iot_v1_iot_proto_rawDescOnce sync.Once
	file_iot_v1_iot_proto_rawDescData []byte
)

func file_iot_v1_iot_proto_rawDescGZIP() []byte {
	file_iot_v1_iot_proto_rawDescOnce.Do(func() {
		file_iot_v1_iot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iot_v1_iot_proto_rawDesc), len(file_iot_v1_iot_proto_rawDesc)))
	})
	return file_iot_v1_iot_proto_rawDescData
}

var file_iot_v1_iot_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_iot_v1_iot_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_iot_v1_iot_proto_goTypes = []any{
	(ColorTemperature)(0),            // 0: iot.v1.ColorTemperature
	(Brightness)(0),                  // 1: iot.v1.Brightness
	(ZoneState)(0),                   // 2: iot.v1.ZoneState
	(DeviceType)(0),                  // 3: iot.v1.DeviceType
	(*UpdateDeviceResponse)(nil),     // 4: iot.v1.UpdateDeviceResponse
	(*DeviceDiscovery)(nil),          // 5: iot.v1.DeviceDiscovery
	(*UpdateDeviceRequest)(nil),      // 6: iot.v1.UpdateDeviceRequest
	(*AlertRequest)(nil),             // 7: iot.v1.AlertRequest
	(*AlertResponse)(nil),            // 8: iot.v1.AlertResponse
	(*EpochRequest)(nil),             // 9: iot.v1.EpochRequest
	(*EpochResponse)(nil),            // 10: iot.v1.EpochResponse
	(*SendRequest)(nil),              // 11: iot.v1.SendRequest
	(*SendResponse)(nil),             // 12: iot.v1.SendResponse
	(*SetStateResponse)(nil),         // 13: iot.v1.SetStateResponse
	(*SetStateRequest)(nil),          // 14: iot.v1.SetStateRequest
	(*SetSceneResponse)(nil),         // 15: iot.v1.SetSceneResponse
	(*SetSceneRequest)(nil),          // 16: iot.v1.SetSceneRequest
	(*GetDeviceZoneRequest)(nil),     // 17: iot.v1.GetDeviceZoneRequest
	(*GetDeviceZoneResponse)(nil),    // 18: iot.v1.GetDeviceZoneResponse
	(*ActionHandlerRequest)(nil),     // 19: iot.v1.ActionHandlerRequest
	(*ActionHandlerResponse)(nil),    // 20: iot.v1.ActionHandlerResponse
	(*SelfAnnounceRequest)(nil),      // 21: iot.v1.SelfAnnounceRequest
	(*SelfAnnounceResponse)(nil),     // 22: iot.v1.SelfAnnounceResponse
	(*OccupancyHandlerRequest)(nil),  // 23: iot.v1.OccupancyHandlerRequest
	(*OccupancyHandlerResponse)(nil), // 24: iot.v1.OccupancyHandlerResponse
	(*Device)(nil),                   // 25: iot.v1.Device
}
var file_iot_v1_iot_proto_depIdxs = []int32{
	2,  // 0: iot.v1.SetStateRequest.state:type_name -> iot.v1.ZoneState
	3,  // 1: iot.v1.Device.type:type_name -> iot.v1.DeviceType
	6,  // 2: iot.v1.IOTService.UpdateDevice:input_type -> iot.v1.UpdateDeviceRequest
	7,  // 3: iot.v1.EventReceiverService.Alert:input_type -> iot.v1.AlertRequest
	9,  // 4: iot.v1.EventReceiverService.Epoch:input_type -> iot.v1.EpochRequest
	11, // 5: iot.v1.RouteService.Send:input_type -> iot.v1.SendRequest
	14, // 6: iot.v1.ZoneKeeperService.SetState:input_type -> iot.v1.SetStateRequest
	16, // 7: iot.v1.ZoneKeeperService.SetScene:input_type -> iot.v1.SetSceneRequest
	17, // 8: iot.v1.ZoneKeeperService.GetDeviceZone:input_type -> iot.v1.GetDeviceZoneRequest
	19, // 9: iot.v1.ZoneKeeperService.ActionHandler:input_type -> iot.v1.ActionHandlerRequest
	21, // 10: iot.v1.ZoneKeeperService.SelfAnnounce:input_type -> iot.v1.SelfAnnounceRequest
	23, // 11: iot.v1.ZoneKeeperService.OccupancyHandler:input_type -> iot.v1.OccupancyHandlerRequest
	4,  // 12: iot.v1.IOTService.UpdateDevice:output_type -> iot.v1.UpdateDeviceResponse
	8,  // 13: iot.v1.EventReceiverService.Alert:output_type -> iot.v1.AlertResponse
	10, // 14: iot.v1.EventReceiverService.Epoch:output_type -> iot.v1.EpochResponse
	12, // 15: iot.v1.RouteService.Send:output_type -> iot.v1.SendResponse
	13, // 16: iot.v1.ZoneKeeperService.SetState:output_type -> iot.v1.SetStateResponse
	15, // 17: iot.v1.ZoneKeeperService.SetScene:output_type -> iot.v1.SetSceneResponse
	18, // 18: iot.v1.ZoneKeeperService.GetDeviceZone:output_type -> iot.v1.GetDeviceZoneResponse
	20, // 19: iot.v1.ZoneKeeperService.ActionHandler:output_type -> iot.v1.ActionHandlerResponse
	22, // 20: iot.v1.ZoneKeeperService.SelfAnnounce:output_type -> iot.v1.SelfAnnounceResponse
	24, // 21: iot.v1.ZoneKeeperService.OccupancyHandler:output_type -> iot.v1.OccupancyHandlerResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_iot_v1_iot_proto_init() }
func file_iot_v1_iot_proto_init() {
	if File_iot_v1_iot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iot_v1_iot_proto_rawDesc), len(file_iot_v1_iot_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_iot_v1_iot_proto_goTypes,
		DependencyIndexes: file_iot_v1_iot_proto_depIdxs,
		EnumInfos:         file_iot_v1_iot_proto_enumTypes,
		MessageInfos:      file_iot_v1_iot_proto_msgTypes,
	}.Build()
	File_iot_v1_iot_proto = out.File
	file_iot_v1_iot_proto_goTypes = nil
	file_iot_v1_iot_proto_depIdxs = nil
}
