// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: iot/v1/iot.proto

package iotv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IOTServiceClient is the client API for IOTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IOTServiceClient interface {
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error)
}

type iOTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIOTServiceClient(cc grpc.ClientConnInterface) IOTServiceClient {
	return &iOTServiceClient{cc}
}

func (c *iOTServiceClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error) {
	out := new(UpdateDeviceResponse)
	err := c.cc.Invoke(ctx, "/iot.v1.IOTService/UpdateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IOTServiceServer is the server API for IOTService service.
// All implementations should embed UnimplementedIOTServiceServer
// for forward compatibility
type IOTServiceServer interface {
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error)
}

// UnimplementedIOTServiceServer should be embedded to have forward compatible implementations.
type UnimplementedIOTServiceServer struct {
}

func (UnimplementedIOTServiceServer) UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}

// UnsafeIOTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IOTServiceServer will
// result in compilation errors.
type UnsafeIOTServiceServer interface {
	mustEmbedUnimplementedIOTServiceServer()
}

func RegisterIOTServiceServer(s grpc.ServiceRegistrar, srv IOTServiceServer) {
	s.RegisterService(&IOTService_ServiceDesc, srv)
}

func _IOTService_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOTServiceServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot.v1.IOTService/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOTServiceServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IOTService_ServiceDesc is the grpc.ServiceDesc for IOTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IOTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.v1.IOTService",
	HandlerType: (*IOTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDevice",
			Handler:    _IOTService_UpdateDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iot/v1/iot.proto",
}

// AlertReceiverServiceClient is the client API for AlertReceiverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertReceiverServiceClient interface {
	Alert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error)
}

type alertReceiverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertReceiverServiceClient(cc grpc.ClientConnInterface) AlertReceiverServiceClient {
	return &alertReceiverServiceClient{cc}
}

func (c *alertReceiverServiceClient) Alert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error) {
	out := new(AlertResponse)
	err := c.cc.Invoke(ctx, "/iot.v1.AlertReceiverService/Alert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertReceiverServiceServer is the server API for AlertReceiverService service.
// All implementations should embed UnimplementedAlertReceiverServiceServer
// for forward compatibility
type AlertReceiverServiceServer interface {
	Alert(context.Context, *AlertRequest) (*AlertResponse, error)
}

// UnimplementedAlertReceiverServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAlertReceiverServiceServer struct {
}

func (UnimplementedAlertReceiverServiceServer) Alert(context.Context, *AlertRequest) (*AlertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Alert not implemented")
}

// UnsafeAlertReceiverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertReceiverServiceServer will
// result in compilation errors.
type UnsafeAlertReceiverServiceServer interface {
	mustEmbedUnimplementedAlertReceiverServiceServer()
}

func RegisterAlertReceiverServiceServer(s grpc.ServiceRegistrar, srv AlertReceiverServiceServer) {
	s.RegisterService(&AlertReceiverService_ServiceDesc, srv)
}

func _AlertReceiverService_Alert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertReceiverServiceServer).Alert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot.v1.AlertReceiverService/Alert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertReceiverServiceServer).Alert(ctx, req.(*AlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertReceiverService_ServiceDesc is the grpc.ServiceDesc for AlertReceiverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertReceiverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.v1.AlertReceiverService",
	HandlerType: (*AlertReceiverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Alert",
			Handler:    _AlertReceiverService_Alert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iot/v1/iot.proto",
}

// ZoneServiceClient is the client API for ZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZoneServiceClient interface {
	SetState(ctx context.Context, in *ZoneServiceSetStateRequest, opts ...grpc.CallOption) (*ZoneServiceSetStateResponse, error)
}

type zoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZoneServiceClient(cc grpc.ClientConnInterface) ZoneServiceClient {
	return &zoneServiceClient{cc}
}

func (c *zoneServiceClient) SetState(ctx context.Context, in *ZoneServiceSetStateRequest, opts ...grpc.CallOption) (*ZoneServiceSetStateResponse, error) {
	out := new(ZoneServiceSetStateResponse)
	err := c.cc.Invoke(ctx, "/iot.v1.ZoneService/SetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZoneServiceServer is the server API for ZoneService service.
// All implementations should embed UnimplementedZoneServiceServer
// for forward compatibility
type ZoneServiceServer interface {
	SetState(context.Context, *ZoneServiceSetStateRequest) (*ZoneServiceSetStateResponse, error)
}

// UnimplementedZoneServiceServer should be embedded to have forward compatible implementations.
type UnimplementedZoneServiceServer struct {
}

func (UnimplementedZoneServiceServer) SetState(context.Context, *ZoneServiceSetStateRequest) (*ZoneServiceSetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}

// UnsafeZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZoneServiceServer will
// result in compilation errors.
type UnsafeZoneServiceServer interface {
	mustEmbedUnimplementedZoneServiceServer()
}

func RegisterZoneServiceServer(s grpc.ServiceRegistrar, srv ZoneServiceServer) {
	s.RegisterService(&ZoneService_ServiceDesc, srv)
}

func _ZoneService_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZoneServiceSetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZoneServiceServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot.v1.ZoneService/SetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZoneServiceServer).SetState(ctx, req.(*ZoneServiceSetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZoneService_ServiceDesc is the grpc.ServiceDesc for ZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iot.v1.ZoneService",
	HandlerType: (*ZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetState",
			Handler:    _ZoneService_SetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iot/v1/iot.proto",
}
