# permissions for end users to edit devicetypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: devicetype-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: iotcontroller
    app.kubernetes.io/part-of: iotcontroller
    app.kubernetes.io/managed-by: kustomize
  name: devicetype-editor-role
rules:
- apiGroups:
  - iot.iot
  resources:
  - devicetypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iot
  resources:
  - devicetypes/status
  verbs:
  - get
