---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iot.iot
  resources:
  - devices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iot
  resources:
  - devices/finalizers
  verbs:
  - update
- apiGroups:
  - iot.iot
  resources:
  - devices/status
  verbs:
  - get
  - patch
  - update
