# permissions for end users to view zones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zone-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: iotcontroller
    app.kubernetes.io/part-of: iotcontroller
    app.kubernetes.io/managed-by: kustomize
  name: zone-viewer-role
rules:
- apiGroups:
  - iot.iot
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iot.iot
  resources:
  - zones/status
  verbs:
  - get
