// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: zigbee/v1/zigbee.proto

package zigbeev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NetworkState represents the current state of a Zigbee network node.
// Based on EmberNetworkStatus from EmberZNet/EZSP (values 0-6) and DeviceState from Z-Stack.
// This is a unified abstraction that maps both Ember and Z-Stack states.
type NetworkState int32

const (
	NetworkState_NETWORK_STATE_UNSPECIFIED NetworkState = 0
	// The node is not associated with a network in any way.
	// Maps to: EmberNetworkStatus.NO_NETWORK (0), Z-Stack DeviceState.InitializedNotStarted
	NetworkState_NETWORK_STATE_NO_NETWORK NetworkState = 1
	// The node is currently attempting to join a network.
	// Maps to: EmberNetworkStatus.JOINING_NETWORK (1), Z-Stack DeviceState.Joining
	NetworkState_NETWORK_STATE_JOINING_NETWORK NetworkState = 2
	// The node is joined to a network and operational.
	// Maps to: EmberNetworkStatus.JOINED_NETWORK (2), Z-Stack DeviceState.Coordinator/Router/EndDevice
	NetworkState_NETWORK_STATE_JOINED_NETWORK NetworkState = 3
	// The node is an end device joined to a network but its parent is not responding.
	// Maps to: EmberNetworkStatus.JOINED_NETWORK_NO_PARENT (3), Z-Stack DeviceState.Orphan
	NetworkState_NETWORK_STATE_JOINED_NETWORK_NO_PARENT NetworkState = 4
	// The node is in the process of leaving its current network.
	// Maps to: EmberNetworkStatus.LEAVING_NETWORK (6)
	NetworkState_NETWORK_STATE_LEAVING_NETWORK NetworkState = 5
)

// Enum value maps for NetworkState.
var (
	NetworkState_name = map[int32]string{
		0: "NETWORK_STATE_UNSPECIFIED",
		1: "NETWORK_STATE_NO_NETWORK",
		2: "NETWORK_STATE_JOINING_NETWORK",
		3: "NETWORK_STATE_JOINED_NETWORK",
		4: "NETWORK_STATE_JOINED_NETWORK_NO_PARENT",
		5: "NETWORK_STATE_LEAVING_NETWORK",
	}
	NetworkState_value = map[string]int32{
		"NETWORK_STATE_UNSPECIFIED":              0,
		"NETWORK_STATE_NO_NETWORK":               1,
		"NETWORK_STATE_JOINING_NETWORK":          2,
		"NETWORK_STATE_JOINED_NETWORK":           3,
		"NETWORK_STATE_JOINED_NETWORK_NO_PARENT": 4,
		"NETWORK_STATE_LEAVING_NETWORK":          5,
	}
)

func (x NetworkState) Enum() *NetworkState {
	p := new(NetworkState)
	*p = x
	return p
}

func (x NetworkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkState) Descriptor() protoreflect.EnumDescriptor {
	return file_zigbee_v1_zigbee_proto_enumTypes[0].Descriptor()
}

func (NetworkState) Type() protoreflect.EnumType {
	return &file_zigbee_v1_zigbee_proto_enumTypes[0]
}

func (x NetworkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkState.Descriptor instead.
func (NetworkState) EnumDescriptor() ([]byte, []int) {
	return file_zigbee_v1_zigbee_proto_rawDescGZIP(), []int{0}
}

// NetworkInfo contains information about the current Zigbee network state.
type NetworkInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ShortAddress          uint32                 `protobuf:"varint,1,opt,name=short_address,json=shortAddress,proto3" json:"short_address,omitempty"`                              // 16-bit network address (node ID)
	PanId                 uint32                 `protobuf:"varint,2,opt,name=pan_id,json=panId,proto3" json:"pan_id,omitempty"`                                                   // 16-bit PAN ID
	ParentAddress         uint32                 `protobuf:"varint,3,opt,name=parent_address,json=parentAddress,proto3" json:"parent_address,omitempty"`                           // 16-bit parent node address
	ExtendedPanId         uint64                 `protobuf:"varint,4,opt,name=extended_pan_id,json=extendedPanId,proto3" json:"extended_pan_id,omitempty"`                         // 64-bit Extended PAN ID
	ExtendedParentAddress uint64                 `protobuf:"varint,5,opt,name=extended_parent_address,json=extendedParentAddress,proto3" json:"extended_parent_address,omitempty"` // 64-bit Extended Parent Address (EUI64)
	Channel               uint32                 `protobuf:"varint,6,opt,name=channel,proto3" json:"channel,omitempty"`                                                            // Radio channel (11-26 for 2.4GHz)
	State                 NetworkState           `protobuf:"varint,7,opt,name=state,proto3,enum=zigbee.v1.NetworkState" json:"state,omitempty"`                                    // Current network state
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_zigbee_v1_zigbee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_v1_zigbee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_zigbee_v1_zigbee_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkInfo) GetShortAddress() uint32 {
	if x != nil {
		return x.ShortAddress
	}
	return 0
}

func (x *NetworkInfo) GetPanId() uint32 {
	if x != nil {
		return x.PanId
	}
	return 0
}

func (x *NetworkInfo) GetParentAddress() uint32 {
	if x != nil {
		return x.ParentAddress
	}
	return 0
}

func (x *NetworkInfo) GetExtendedPanId() uint64 {
	if x != nil {
		return x.ExtendedPanId
	}
	return 0
}

func (x *NetworkInfo) GetExtendedParentAddress() uint64 {
	if x != nil {
		return x.ExtendedParentAddress
	}
	return 0
}

func (x *NetworkInfo) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *NetworkInfo) GetState() NetworkState {
	if x != nil {
		return x.State
	}
	return NetworkState_NETWORK_STATE_UNSPECIFIED
}

// NetworkParameters defines the parameters for forming or joining a Zigbee network.
// These parameters must be consistent across device swaps to maintain the same network.
type NetworkParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PanId         uint32                 `protobuf:"varint,1,opt,name=pan_id,json=panId,proto3" json:"pan_id,omitempty"`                           // 16-bit PAN ID
	ExtendedPanId uint64                 `protobuf:"varint,2,opt,name=extended_pan_id,json=extendedPanId,proto3" json:"extended_pan_id,omitempty"` // 64-bit Extended PAN ID
	Channel       uint32                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`                                    // Radio channel (11-26 for 2.4GHz)
	NetworkKey    []byte                 `protobuf:"bytes,4,opt,name=network_key,json=networkKey,proto3" json:"network_key,omitempty"`             // 128-bit (16 bytes) Network Key for encryption
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkParameters) Reset() {
	*x = NetworkParameters{}
	mi := &file_zigbee_v1_zigbee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkParameters) ProtoMessage() {}

func (x *NetworkParameters) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_v1_zigbee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkParameters.ProtoReflect.Descriptor instead.
func (*NetworkParameters) Descriptor() ([]byte, []int) {
	return file_zigbee_v1_zigbee_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkParameters) GetPanId() uint32 {
	if x != nil {
		return x.PanId
	}
	return 0
}

func (x *NetworkParameters) GetExtendedPanId() uint64 {
	if x != nil {
		return x.ExtendedPanId
	}
	return 0
}

func (x *NetworkParameters) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *NetworkParameters) GetNetworkKey() []byte {
	if x != nil {
		return x.NetworkKey
	}
	return nil
}

// PersistedNetworkState represents the network state saved to disk.
// This allows the same network to be restored when swapping devices.
type PersistedNetworkState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PanId         uint32                 `protobuf:"varint,1,opt,name=pan_id,json=panId,proto3" json:"pan_id,omitempty"`
	ExtendedPanId uint64                 `protobuf:"varint,2,opt,name=extended_pan_id,json=extendedPanId,proto3" json:"extended_pan_id,omitempty"`
	Channel       uint32                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	NetworkKey    []byte                 `protobuf:"bytes,4,opt,name=network_key,json=networkKey,proto3" json:"network_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistedNetworkState) Reset() {
	*x = PersistedNetworkState{}
	mi := &file_zigbee_v1_zigbee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedNetworkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedNetworkState) ProtoMessage() {}

func (x *PersistedNetworkState) ProtoReflect() protoreflect.Message {
	mi := &file_zigbee_v1_zigbee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedNetworkState.ProtoReflect.Descriptor instead.
func (*PersistedNetworkState) Descriptor() ([]byte, []int) {
	return file_zigbee_v1_zigbee_proto_rawDescGZIP(), []int{2}
}

func (x *PersistedNetworkState) GetPanId() uint32 {
	if x != nil {
		return x.PanId
	}
	return 0
}

func (x *PersistedNetworkState) GetExtendedPanId() uint64 {
	if x != nil {
		return x.ExtendedPanId
	}
	return 0
}

func (x *PersistedNetworkState) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PersistedNetworkState) GetNetworkKey() []byte {
	if x != nil {
		return x.NetworkKey
	}
	return nil
}

var File_zigbee_v1_zigbee_proto protoreflect.FileDescriptor

const file_zigbee_v1_zigbee_proto_rawDesc = "" +
	"\n" +
	"\x16zigbee/v1/zigbee.proto\x12\tzigbee.v1\"\x99\x02\n" +
	"\vNetworkInfo\x12#\n" +
	"\rshort_address\x18\x01 \x01(\rR\fshortAddress\x12\x15\n" +
	"\x06pan_id\x18\x02 \x01(\rR\x05panId\x12%\n" +
	"\x0eparent_address\x18\x03 \x01(\rR\rparentAddress\x12&\n" +
	"\x0fextended_pan_id\x18\x04 \x01(\x04R\rextendedPanId\x126\n" +
	"\x17extended_parent_address\x18\x05 \x01(\x04R\x15extendedParentAddress\x12\x18\n" +
	"\achannel\x18\x06 \x01(\rR\achannel\x12-\n" +
	"\x05state\x18\a \x01(\x0e2\x17.zigbee.v1.NetworkStateR\x05state\"\x8d\x01\n" +
	"\x11NetworkParameters\x12\x15\n" +
	"\x06pan_id\x18\x01 \x01(\rR\x05panId\x12&\n" +
	"\x0fextended_pan_id\x18\x02 \x01(\x04R\rextendedPanId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x1f\n" +
	"\vnetwork_key\x18\x04 \x01(\fR\n" +
	"networkKey\"\x91\x01\n" +
	"\x15PersistedNetworkState\x12\x15\n" +
	"\x06pan_id\x18\x01 \x01(\rR\x05panId\x12&\n" +
	"\x0fextended_pan_id\x18\x02 \x01(\x04R\rextendedPanId\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x1f\n" +
	"\vnetwork_key\x18\x04 \x01(\fR\n" +
	"networkKey*\xdf\x01\n" +
	"\fNetworkState\x12\x1d\n" +
	"\x19NETWORK_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18NETWORK_STATE_NO_NETWORK\x10\x01\x12!\n" +
	"\x1dNETWORK_STATE_JOINING_NETWORK\x10\x02\x12 \n" +
	"\x1cNETWORK_STATE_JOINED_NETWORK\x10\x03\x12*\n" +
	"&NETWORK_STATE_JOINED_NETWORK_NO_PARENT\x10\x04\x12!\n" +
	"\x1dNETWORK_STATE_LEAVING_NETWORK\x10\x05B\x9b\x01\n" +
	"\rcom.zigbee.v1B\vZigbeeProtoP\x01Z8github.com/zachfi/iotcontroller/proto/zigbee/v1;zigbeev1\xa2\x02\x03ZXX\xaa\x02\tZigbee.V1\xca\x02\tZigbee\\V1\xe2\x02\x15Zigbee\\V1\\GPBMetadata\xea\x02\n" +
	"Zigbee::V1b\x06proto3"

var (
	file_zigbee_v1_zigbee_proto_rawDescOnce sync.Once
	file_zigbee_v1_zigbee_proto_rawDescData []byte
)

func file_zigbee_v1_zigbee_proto_rawDescGZIP() []byte {
	file_zigbee_v1_zigbee_proto_rawDescOnce.Do(func() {
		file_zigbee_v1_zigbee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zigbee_v1_zigbee_proto_rawDesc), len(file_zigbee_v1_zigbee_proto_rawDesc)))
	})
	return file_zigbee_v1_zigbee_proto_rawDescData
}

var file_zigbee_v1_zigbee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zigbee_v1_zigbee_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zigbee_v1_zigbee_proto_goTypes = []any{
	(NetworkState)(0),             // 0: zigbee.v1.NetworkState
	(*NetworkInfo)(nil),           // 1: zigbee.v1.NetworkInfo
	(*NetworkParameters)(nil),     // 2: zigbee.v1.NetworkParameters
	(*PersistedNetworkState)(nil), // 3: zigbee.v1.PersistedNetworkState
}
var file_zigbee_v1_zigbee_proto_depIdxs = []int32{
	0, // 0: zigbee.v1.NetworkInfo.state:type_name -> zigbee.v1.NetworkState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zigbee_v1_zigbee_proto_init() }
func file_zigbee_v1_zigbee_proto_init() {
	if File_zigbee_v1_zigbee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zigbee_v1_zigbee_proto_rawDesc), len(file_zigbee_v1_zigbee_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zigbee_v1_zigbee_proto_goTypes,
		DependencyIndexes: file_zigbee_v1_zigbee_proto_depIdxs,
		EnumInfos:         file_zigbee_v1_zigbee_proto_enumTypes,
		MessageInfos:      file_zigbee_v1_zigbee_proto_msgTypes,
	}.Build()
	File_zigbee_v1_zigbee_proto = out.File
	file_zigbee_v1_zigbee_proto_goTypes = nil
	file_zigbee_v1_zigbee_proto_depIdxs = nil
}
