// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: telemetry/v1/telemetry.proto

package telemetryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	TelemetryReportIOTDevice(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_TelemetryReportIOTDeviceClient, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) TelemetryReportIOTDevice(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_TelemetryReportIOTDeviceClient, error) {
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], "/telemetry.v1.TelemetryService/TelemetryReportIOTDevice", opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryServiceTelemetryReportIOTDeviceClient{stream}
	return x, nil
}

type TelemetryService_TelemetryReportIOTDeviceClient interface {
	Send(*TelemetryReportIOTDeviceRequest) error
	CloseAndRecv() (*TelemetryReportIOTDeviceResponse, error)
	grpc.ClientStream
}

type telemetryServiceTelemetryReportIOTDeviceClient struct {
	grpc.ClientStream
}

func (x *telemetryServiceTelemetryReportIOTDeviceClient) Send(m *TelemetryReportIOTDeviceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *telemetryServiceTelemetryReportIOTDeviceClient) CloseAndRecv() (*TelemetryReportIOTDeviceResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TelemetryReportIOTDeviceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations should embed UnimplementedTelemetryServiceServer
// for forward compatibility
type TelemetryServiceServer interface {
	TelemetryReportIOTDevice(TelemetryService_TelemetryReportIOTDeviceServer) error
}

// UnimplementedTelemetryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTelemetryServiceServer struct {
}

func (UnimplementedTelemetryServiceServer) TelemetryReportIOTDevice(TelemetryService_TelemetryReportIOTDeviceServer) error {
	return status.Errorf(codes.Unimplemented, "method TelemetryReportIOTDevice not implemented")
}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_TelemetryReportIOTDevice_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServiceServer).TelemetryReportIOTDevice(&telemetryServiceTelemetryReportIOTDeviceServer{stream})
}

type TelemetryService_TelemetryReportIOTDeviceServer interface {
	SendAndClose(*TelemetryReportIOTDeviceResponse) error
	Recv() (*TelemetryReportIOTDeviceRequest, error)
	grpc.ServerStream
}

type telemetryServiceTelemetryReportIOTDeviceServer struct {
	grpc.ServerStream
}

func (x *telemetryServiceTelemetryReportIOTDeviceServer) SendAndClose(m *TelemetryReportIOTDeviceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *telemetryServiceTelemetryReportIOTDeviceServer) Recv() (*TelemetryReportIOTDeviceRequest, error) {
	m := new(TelemetryReportIOTDeviceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.v1.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TelemetryReportIOTDevice",
			Handler:       _TelemetryService_TelemetryReportIOTDevice_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry/v1/telemetry.proto",
}
